### ISSUE TITLE
Help - Tracker connection 

### ISSUE THREAD

**Issue by 42CrMo4** [eifinger/hass-fressnapf-tracker#21]
Hello,

thank you for this integration. Unfortnatly I was not succesfull to connect the tracker. Mabey I'm doing something wrong. 
In the package I have a leaflet with the following information:

Seriennummer - Serialnumber (9 digit numeric)
Schlüsselnummer - "key number" (8 digit numeric)
QR code with 24 digit only letters

I tried both the numbers and letters for either the device and auth token. Both seem not to work. I will always get following error in the log. 

```
Error while setting up fressnapf_tracker platform for device_tracker

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fressnapf_tracker/device_tracker.py", line 27, in async_setup_entry
    FressnapfTrackerDeviceTracker(
  File "/config/custom_components/fressnapf_tracker/device_tracker.py", line 44, in __init__
    super().__init__(coordinator, tracker_id)
  File "/config/custom_components/fressnapf_tracker/entity.py", line 22, in __init__
    name=str(self.coordinator.data["name"]),
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
```

Most proberly I'm doing something wrone. I would appreciate your help. Thank you.

**Comment by 42CrMo4** [comment]
Thank you for the feedback. That might be beyond my capabilities :wink:
But I would be very intrested in using it, If you ever find the time and effort to document or integrate it.

**Comment by vitruvo** [comment]
Ive had those same questions and decided to put this project aside for now as I'm quite busy with other stuff right now. I hover accidentally came across a super helpful app for iOS that allows you to install a local proxy right on your device and receive a very comfortable overview over all http-calls that are made from your phone.. long story short: this is a rather easy way to determine the needed values for this integration (if you're on iOS).
check out https://apps.apple.com/us/app/proxyman-network-debug-tool/id1551292695
hope that helps

**Comment by eifinger** [comment]
There won't be any help in this repository with getting the tokens. There are guides in other places like the home assistant forum
