### ISSUE TITLE
A second tracker cannot be added

### ISSUE THREAD

**Issue by vitruvo** [eifinger/hass-fressnapf-tracker#35]
hi!

once I try to add a second tracker for a second dog, the setup routine returns an error 500.
I have way too little knowledge to estimate how much effort it takes to solve this, but just in case this is a no-brainer, a fix would be greatly appreciated and reward with coffee! ;-)

thanks for your great work so far! 👍

**Comment by eifinger** [comment]
Hi @vitruvo, thank you for opening an issue about that.

Can you give me some logs for that?
Can you also tell me if you setup the second tracker with completely different serial_number, device_token and auth_token? Or did some of them stay the same?

I only have a single tracker and have not seen the traffic for adding a second one.

**Comment by vitruvo** [comment]
HI @eifinger, I´ll do my best to support! :-)

All I get is this 500 error when trying to add a second tracker:
![image](https://github.com/eifinger/hass-fressnapf-tracker/assets/869740/b2b64ce9-4ee4-4be4-a3ad-14b859f2def6)

within the logs I see smth like this, what MIGHT be related to the issue:
![image](https://github.com/eifinger/hass-fressnapf-tracker/assets/869740/84fd5143-152e-4f7f-aa7e-d5497516bd19)

from what I can see, the serial numbers(of course) and the deviceToken are different, the authToken though seems to be the same...

Hope that helps. ✌️

**Comment by eifinger** [comment]
> HI @eifinger, I´ll do my best to support! :-)
> 
> All I get is this 500 error when trying to add a second tracker: ![image](https://private-user-images.githubusercontent.com/869740/289567538-b2b64ce9-4ee4-4be4-a3ad-14b859f2def6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDU1OTIsIm5iZiI6MTcwMjMwNTI5MiwicGF0aCI6Ii84Njk3NDAvMjg5NTY3NTM4LWIyYjY0Y2U5LTRlZTQtNGJlNC1hM2FkLTE0Yjg1OWYyZGVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNDM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODI0NTFmNzFlYzgzMjcyZGFmNWJkYTYzOTNlMzkwOTM1ZmI1OGM5YzMzMzUxNjYxMjdjODJkYTAzZGNlZjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Yrm84abGImexfJpGkdKqkKpEXk879j-iyp8btIs7j0)
> 
> within the logs I see smth like this, what MIGHT be related to the issue: ![image](https://private-user-images.githubusercontent.com/869740/289567748-84fd5143-152e-4f7f-aa7e-d5497516bd19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDU1OTIsIm5iZiI6MTcwMjMwNTI5MiwicGF0aCI6Ii84Njk3NDAvMjg5NTY3NzQ4LTg0ZmQ1MTQzLTE1MmUtNGY3Zi1hYTdlLWQ1NDk3NTE2YmQxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNDM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzM3YjcwZDAwNjJjMWZmZGE4ODI5ZjI5NWI1NTVlOGRhNmJlNWY4ZjFlZjNmNDAwZTBhY2FiYzVhNDk2YzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KP2UzYBZziOKJxMjxTkH8Ok38lbrgJHU-ORWYEXrNbk)
> 
> from what I can see, the serial numbers(of course) and the deviceToken are different, the authToken though seems to be the same...
> 
> Hope that helps. ✌️

Found the issue.

**Comment by eifinger** [comment]
Please try again with the new version v0.1.2
