### ISSUE TITLE
Unknown error occurred when trying to add tracker without a LED

### ISSUE THREAD

**Issue by bapfnet** [eifinger/hass-fressnapf-tracker#66]
After installing and looking for the three required values I just got an "Unknown error occurred"
![err](https://github.com/user-attachments/assets/79a40795-e055-4ba7-80e3-12737850ded9)

**Comment by eifinger** [comment]
Could you please enable debug logging and share the logs?

**Comment by eifinger** [comment]
Thank you!
This says your tracker does not have a LED. I will fix that.

Can you provide a picture of your tracker? I wasn't aware there is more than one type

**Comment by bapfnet** [comment]
Thank you, this would be great!

![tracker](https://github.com/user-attachments/assets/1c524553-e796-4933-915c-3f8c6e6d7a0e)

**Comment by bapfnet** [comment]
After editing the part below in client.py the integration of the device was successful.

```
def _transform_result(result: dict[str, Any]) -> dict[str, Any]:
    """Flatten some entries and handle missing values."""
    
    # Überprüfen, ob die Werte None sind und gegebenenfalls Standardwerte setzen
    led_brightness = result.get("led_brightness", {})
    deep_sleep = result.get("deep_sleep", {})
    led_activatable = result.get("led_activatable", {})

    result["led_brightness_value"] = led_brightness.get("value", 0) if isinstance(led_brightness, dict) else 0
    result["led_brightness_status"] = led_brightness.get("status", "unknown") if isinstance(led_brightness, dict) else "unknown"
    result["led_activatable_overall"] = led_activatable.get("overall", False) if isinstance(led_activatable, dict) else False
    result["deep_sleep_value"] = deep_sleep.get("value", False) if isinstance(deep_sleep, dict) else False
    result["deep_sleep_status"] = deep_sleep.get("status", "unknown") if isinstance(deep_sleep, dict) else "unknown"

    return result
```

Do you have any idea how to get the coordinates from the tracker?

**Comment by eifinger** [comment]
@bapfnet v1.3.1 will be available in a few minutes. This should fully support your tracker variant. Please give it a try!
